wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.17.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1717705392
    t:
      1:
      - 55
      - 95
      2:
      - 55
      - 95
      3:
      - 2
      - 23
      4: 3.12.3
      5: 0.17.0
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
